travis:
  secure:
    BINSTAR_TOKEN: s7B2/G1EOOmh0jloPhEEFdY9bI5p9vxVmutpenwATpeuSmRg6JeHx86uWWbCluFfa91RTrIjOwgcGmvgC2gl7YRls8IAYlfpwQFbY8yj9h/jIWEfvWaBJ6DOGJu1DImmC2VW2q2AIpqYtuoclq7CCwmVyFxaK17Ol0GB8p1HRLhsDYGZk4JYoV+jGWR3XEpMOw9Kp6fe0LYB7lNcmE/mBv9cDVP1kyKEfhIOobsU5Ip5krb24BDqGX3i+RFupmyViGfeaLKBi9sDVZrGkuSIFP07WdOQgZ4+YvHeh9+t1kyhmLjgFblxTfkwGFAnuekiKgohFV6MtnXcio907j6PcKPA9NLOfikMnE0IOe88Z3XKsYAZ6NPJ20Nvi7c9GlS15+Ke/Yzg3BnlcqUvsCNYZpun7r00Qkgx+mDK1FloIilf0b7rI0fJ69+9+Dq//3VPBVHzJQMA7JE9AeMhXNcaRPWScQ5TEbqc4zh4Z2ctVgnk5caAR0sNRjctonfE8f6koVzORJFhaPczqxjJYkJhILonAf55lnIn/cbjTMm7IniywPONgZqME5UIoHtsXUJXWCHQVWly+XWGke0ltm2+l8GOy8XnRKL11Ao02KoeveZiCC7OuFgKPGL7NOmPZNAO31jWfU9Ma7GOlgCqH3tz3I3lFKiEs4FvKPoMypQjhuo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
